# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'JALiveShow' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
pod 'Masonry'
pod 'AFNetworking'
pod 'ReactiveObjC'
pod 'MJExtension'
pod 'MJRefresh'
  # Pods for JALiveShow

  target 'JALiveShowTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'JALiveShowUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
